### Get all trades
GET http://localhost:8080/api/trades
Accept: application/json

### Get trade by ID
GET http://localhost:8080/api/trades/100001
Accept: application/json


Advanced Searches
### Search trades by all criteria (names)
GET http://localhost:8080/api/dashboard/search?counterparty=BigBank&bookId=1000&trader=Simon%King&status=LIVE&startDate=2024-06-01&endDate=2024-06-30
Accept: application/json

### Search trades by counterparty only
GET http://localhost:8080/api/dashboard/search?counterparty=BigBank
Accept: application/json

### Search trades by book only
GET http://localhost:8080/api/dashboard/search?bookId=1000
Accept: application/json

### Search trades by trader only
GET http://localhost:8080/api/dashboard/search?trader=Simon%King
Accept: application/json

### Search trades by status only
GET http://localhost:8080/api/dashboard/search?status=LIVE
Accept: application/json

### Search trades by date range only
GET http://localhost:8080/api/dashboard/search?startDate=2024-06-01&endDate=2024-06-30
Accept: application/json

### RSQL query Search by counterparty AND tradeStatus
GET http://localhost:8080/api/dashboard/rsql?query=counterparty.name==BIGBANK;tradeStatus.tradeStatus==LIVE
### RSQl query Comparison
GET http://localhost:8080/api/dashboard/rsql?query=counterparty.name==ABC

### More complex RSQl query
GET http://localhost:8080/api/dashboard/rsql?query=tradeDate=ge=2024-06-01;tradeDate=le=2024-06-30

### RSQL Get all trades where the status is either LIVE or NEW.
GET http://localhost:8080/api/dashboard/rsql?query=tradeStatus.tradeStatus=in=(LIVE,NEW)

### RSQL Get all trades that are not TERMINATED or CANCELLED
GET http://localhost:8080/api/dashboard/rsql?query=tradeStatus.tradeStatus=out=(TERMINATED,CANCELLED)

### returns all names containing “bank” (e.g., “BigBank”, “MegaBank”).

GET http://localhost:8080/api/dashboard/rsql?query=counterparty.name=like=*bank*


### EXPORTING NONSTANDARD SETTLEMENTS
Full CSV (same as before):
GET http://localhost:8080/api/trades/exports/settlements
Non-standard-only CSV:
GET http://localhost:8080/api/trades/exports/settlements?nonStandardOnly=true
